### ISSUE TITLE
\index.ts is missing from the TypeScript compilation error with angular 

### ISSUE THREAD

**Issue by zusrut** [roman-yerin/vertojs#1]
Hi. Got an error with angular 8 after `npm install vertojs` and imported in a component `import { Verto } from 'vertojs';`

`ERROR in ./node_modules/vertojs/src/index.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: ...\node_modules\vertojs\src\index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (...node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:913:23)
    at plugin.done.then (...node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)`

my project tsconfig.json
`{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "downlevelIteration": true,
    "importHelpers": true,
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "esnext",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2015",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2018",
      "dom"
    ]
  }
}`
i tried to make some changes with include key but was not succeed

**Comment by roman-yerin** [comment]
Try to add to tsconfig.json, compilerOptions section:

```
"paths": {
      "src/*": ["src/*"]
 }
```

**Comment by zusrut** [comment]
thanks but not helped. i tried to do it in various ways.

**Comment by roman-yerin** [comment]
Here is a tsconfig.json for the working project uses this library, hope this helps:

```
{
  "extends": "./tsconfig.paths.json",
  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "downlevelIteration": true,
    "typeRoots": [
      "./node_modules/@types",
      "./types"
    ],
    "jsx": "preserve"
  },
  "exclude": [
    "node_modules",
    "build",
    "README.md",
    "src/sw.js"
  ],
  "include": [
    "src",
    "index.d.ts"
  ]
}
```

If not, I'll ask my colleague who works on that project to comment this issue.

**Comment by zusrut** [comment]
thanks. i added to `tsconfig.json`
`  "include": [
    "./src",
    "node_modules/vertojs"
  ]`
and its been successfully compiled.
 also to help my IDE to resolve all staff i copied `node_modules/vertojs/dist/index.d.ts` to `node_modules/@types/vertojs/index.d.ts`
