### ISSUE TITLE
Using this package with React Native for mobile app

### ISSUE THREAD

**Issue by abdul-razaq** [roman-yerin/vertojs#26]
Hi, thanks for this package. I was wondering if its possible to use this package with React Native. I need to build a video chat application that connects to a Verto Backend. And I haven't found a useful react native Verto package yet. Any pointers as to how to go about using your package for react native. Thanks.

**Comment by roman-yerin** [comment]
I believe, you should be able to use this library without any modification with react native, as everything is pure javascript. If you have some issue, don't hesitate to open one.
